import type { Event } from "./types";

export const MOCK_EVENTS: Event[] = [
  {
    id: "1",
    title: {
      ja: "梅田国際交流パーティー🎉",
      ko: "우메다 국제교류 파티🎉",
      en: "Umeda International Mixer 🎉",
    },
    description: {
      ja: "梅田のルーフトップバーで国際交流パーティーを開催！韓国語・英語・日本語を話す仲間と楽しい夜を過ごしましょう。",
      ko: "우메다 루프탑 바에서 열리는 국제교류 파티! 한국어・영어・일본어를 하는 친구들과 즐거운 밤을 보내요.",
      en: "International mixer party at a rooftop bar in Umeda! Meet people who speak Korean, English, and Japanese.",
    },
    category: "party",
    status: "published",
    date: "2026-04-05",
    timeStart: "19:00",
    timeEnd: "22:00",
    location: {
      ja: "梅田・スカイビル周辺",
      ko: "우메다・스카이빌딩 근처",
      en: "Near Umeda Sky Building",
    },
    imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088?w=800&q=80",
    capacity: 30,
    registrationCount: 17,
    createdBy: "admin",
    createdAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "2",
    title: {
      ja: "難波フードツアー🍜",
      ko: "난바 맛집 투어🍜",
      en: "Namba Food Tour 🍜",
    },
    description: {
      ja: "難波の隠れた名店を一緒に巡るフードツアー！たこ焼き・串カツ・お好み焼きを食べ歩きしましょう。",
      ko: "난바의 숨겨진 맛집을 함께 탐방하는 푸드 투어! 타코야키・꼬치카츠・오코노미야키를 먹으며 돌아다녀요.",
      en: "Explore hidden gems of Namba's food scene together! Takoyaki, kushikatsu, and okonomiyaki crawl.",
    },
    category: "food",
    status: "published",
    date: "2026-04-12",
    timeStart: "17:30",
    timeEnd: "20:30",
    location: {
      ja: "なんばグランド花月前集合",
      ko: "난바 그랜드 카게츠 앞 집합",
      en: "Meet at Namba Grand Kagetsu",
    },
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
    capacity: 15,
    registrationCount: 12,
    createdBy: "admin",
    createdAt: "2026-03-21T10:00:00Z",
  },
  {
    id: "3",
    title: {
      ja: "大阪城公園ピクニック☀️",
      ko: "오사카성 공원 피크닉☀️",
      en: "Osaka Castle Park Picnic ☀️",
    },
    description: {
      ja: "お花見シーズンに大阪城公園でピクニック！各自好きな食べ物・飲み物を持参してください。芝生でリラックスしながら新しい友達を作ろう。",
      ko: "벚꽃 시즌에 오사카성 공원에서 피크닉! 각자 좋아하는 음식・음료를 가져오세요. 잔디밭에서 여유롭게 새 친구들을 사귀어요.",
      en: "Picnic at Osaka Castle Park during cherry blossom season! Bring your own food and drinks. Relax on the lawn and make new friends.",
    },
    category: "meetup",
    status: "published",
    date: "2026-04-19",
    timeStart: "13:00",
    timeEnd: "17:00",
    location: {
      ja: "大阪城公園・西の丸庭園前",
      ko: "오사카성 공원・니시노마루 정원 앞",
      en: "Osaka Castle Park, Nishinomaru Garden entrance",
    },
    imageUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80",
    capacity: null,
    registrationCount: 24,
    createdBy: "admin",
    createdAt: "2026-03-22T10:00:00Z",
  },
  {
    id: "4",
    title: {
      ja: "心斎橋ナイトウォーク🌃",
      ko: "신사이바시 나이트워크🌃",
      en: "Shinsaibashi Night Walk 🌃",
    },
    description: {
      ja: "心斎橋・アメ村エリアの夜の街を一緒に散歩しながら交流しましょう。ショッピングや写真撮影も楽しめます。",
      ko: "신사이바시・아메무라 지역의 야경을 함께 산책하며 교류해요. 쇼핑과 사진 촬영도 즐길 수 있어요.",
      en: "Evening stroll through Shinsaibashi and Amemura area. Great for shopping, photos, and casual conversation.",
    },
    category: "meetup",
    status: "published",
    date: "2026-04-25",
    timeStart: "19:00",
    timeEnd: "21:30",
    location: {
      ja: "心斎橋駅・クリスタ長堀出口集合",
      ko: "신사이바시역・크리스타 나가호리 출구 집합",
      en: "Meet at Shinsaibashi Station, Crysta Nagahori exit",
    },
    imageUrl: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800&q=80",
    capacity: 20,
    registrationCount: 8,
    createdBy: "admin",
    createdAt: "2026-03-23T10:00:00Z",
  },
  {
    id: "5",
    title: {
      ja: "ボードゲームナイト🎲",
      ko: "보드게임 나이트🎲",
      en: "Board Game Night 🎲",
    },
    description: {
      ja: "カフェでボードゲームを楽しもう！初心者でも大丈夫。ゲームの説明から丁寧にします。",
      ko: "카페에서 보드게임을 즐겨요! 초보자도 환영. 게임 설명을 친절하게 해드려요.",
      en: "Board game night at a café! Beginners welcome — we'll explain the rules.",
    },
    category: "culture",
    status: "published",
    date: "2026-05-02",
    timeStart: "18:00",
    timeEnd: "21:00",
    location: {
      ja: "本町・カフェ（詳細は承認後にお知らせ）",
      ko: "혼마치・카페 (상세 주소는 승인 후 안내)",
      en: "Honmachi café (exact address shared after approval)",
    },
    imageUrl: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&q=80",
    capacity: 12,
    registrationCount: 5,
    createdBy: "admin",
    createdAt: "2026-03-23T12:00:00Z",
  },
  {
    id: "6",
    title: {
      ja: "天王寺動物園🦒",
      ko: "텐노지 동물원🦒",
      en: "Tennoji Zoo Trip 🦒",
    },
    description: {
      ja: "天王寺動物園を一緒に見学！大人でも楽しめる大阪の有名動物園。終わったら近くのカフェでお茶しましょう。",
      ko: "텐노지 동물원을 함께 관람해요! 어른도 즐길 수 있는 오사카 유명 동물원. 끝나고 근처 카페에서 차 한 잔 해요.",
      en: "Visit Tennoji Zoo together! Osaka's famous zoo is fun for adults too. Coffee nearby after.",
    },
    category: "culture",
    status: "published",
    date: "2026-05-09",
    timeStart: "11:00",
    timeEnd: "15:00",
    location: {
      ja: "天王寺動物園・正門前",
      ko: "텐노지 동물원・정문 앞",
      en: "Tennoji Zoo main gate",
    },
    imageUrl: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=800&q=80",
    capacity: null,
    registrationCount: 11,
    createdBy: "admin",
    createdAt: "2026-03-23T14:00:00Z",
  },
];
