import type { Event } from "./types";

export const MOCK_EVENTS: Event[] = [
  {
    id: "1",
    title: {
      ja: "フットサル　Football",
      ko: "풋살 Football",
      en: "Futsal Football",
    },
    description: {
      ja: "大阪・上新庄でフットサルをやろう！初心者も大歓迎。運動靴を持ってきてください。",
      ko: "오사카 우에신조에서 풋살! 초보자도 환영. 운동화를 챙겨오세요.",
      en: "Futsal in Osaka Ueshinjō! All levels welcome. Bring your sports shoes.",
    },
    category: "sports",
    status: "published",
    date: "2026-03-31",
    timeStart: "15:00",
    timeEnd: "",
    location: {
      ja: "大阪 上新庄",
      ko: "오사카 우에신조",
      en: "Osaka, Ueshinjō",
    },
    imageUrl: "https://images.unsplash.com/photo-1571498664957-fde285d79857?w=800&q=80",
    capacity: null,
    registrationCount: 7,
    createdBy: "admin",
    createdAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "2",
    title: {
      ja: "🥪Bruschetta Party🎈💫",
      ko: "🥪Bruschetta Party🎈💫",
      en: "🥪Bruschetta Party🎈💫",
    },
    description: {
      ja: "ブルスケッタを食べながらみんなで楽しくパーティー！飲み物・おつまみ持参歓迎。",
      ko: "브루스케타를 먹으며 즐거운 파티! 음료·안주 가져오기 환영.",
      en: "Bruschetta party with great food and good vibes! Feel free to bring drinks or snacks.",
    },
    category: "party",
    status: "published",
    date: "2026-04-10",
    timeStart: "19:00",
    timeEnd: "22:00",
    location: {
      ja: "Osaka（詳細は承認後にお知らせ）",
      ko: "오사카 (상세 주소는 승인 후 안내)",
      en: "Osaka (exact address shared after approval)",
    },
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    capacity: null,
    registrationCount: 1,
    createdBy: "admin",
    createdAt: "2026-03-22T10:00:00Z",
  },
  {
    id: "3",
    title: {
      ja: "KYOTO Picnic🍡🍽️",
      ko: "KYOTO Picnic🍡🍽️",
      en: "KYOTO Picnic 🍡🍽️",
    },
    description: {
      ja: "京都でピクニック！お花見シーズンに合わせてみんなで京都へ。食べ物・飲み物は各自持参。",
      ko: "교토에서 피크닉! 벚꽃 시즌에 맞춰 교토로. 음식·음료는 각자 지참.",
      en: "Picnic in Kyoto! Perfect timing for cherry blossom season. Bring your own food and drinks.",
    },
    category: "meetup",
    status: "published",
    date: "2026-04-12",
    timeStart: "13:00",
    timeEnd: "17:00",
    location: {
      ja: "Kyoto（詳細は承認後にお知らせ）",
      ko: "교토 (상세 주소는 승인 후 안내)",
      en: "Kyoto (exact address shared after approval)",
    },
    imageUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80",
    capacity: null,
    registrationCount: 1,
    createdBy: "admin",
    createdAt: "2026-03-22T12:00:00Z",
  },
];
